#!/bin/bash
# Parent Dashboard Testing Guide
# Run this script to see the testing steps

echo "🧪 PARENT DASHBOARD TESTING GUIDE"
echo "=================================="
echo ""
echo "✅ Dev server is running on: http://localhost:3000"
echo ""
echo "📝 TESTING STEPS:"
echo ""
echo "1️⃣  CREATE A PARENT USER (if not already done)"
echo "   Option A: Use Supabase Dashboard"
echo "   - Go to Authentication > Users"
echo "   - Create user: parent@test.com / password123"
echo "   - Add to 'users' table with role='PARENT'"
echo ""
echo "   Option B: Use existing SUPER_ADMIN"
echo "   - Login as: superadmin@test.com"
echo "   - Go to Admin dashboard"
echo "   - Create parent and link to a child"
echo ""
echo "2️⃣  LINK PARENT TO CHILD"
echo "   In Supabase, insert into parent_child table:"
echo "   INSERT INTO parent_child (parent_id, child_id, relationship)"
echo "   VALUES ('parent-user-id', 1, 'parent');"
echo ""
echo "3️⃣  ADD SAMPLE DATA (for testing)"
echo "   - Attendance log for today"
echo "   - Meal logs"
echo "   - Nap log"
echo "   - Optional: incident report"
echo ""
echo "4️⃣  TEST THE DASHBOARD"
echo "   Visit: http://localhost:3000/dashboard/parent"
echo ""
echo "🎯 WHAT TO TEST:"
echo ""
echo "✓ Overview Dashboard:"
echo "  - Child profile card displays correctly"
echo "  - Today's highlights show (arrival, nap, meals, incidents)"
echo "  - Timeline shows recent activities"
echo "  - Auto-refresh works (wait 30 seconds)"
echo "  - Multi-child selector (if multiple children)"
echo ""
echo "✓ Child Profile Page:"
echo "  - Click 'View Full Profile & History'"
echo "  - Medical info displays if present"
echo "  - Attendance tab shows 30-day history"
echo "  - Meals tab shows 7-day meals"
echo "  - Naps tab shows 7-day naps"
echo "  - Incidents tab shows 30-day incidents"
echo "  - Stats calculate correctly"
echo ""
echo "✓ Timeline Page:"
echo "  - Click 'View Full Timeline'"
echo "  - Today's events display chronologically"
echo "  - Icons and colors correct"
echo "  - Date navigation works (prev/next)"
echo "  - Jump to Today button works"
echo ""
echo "✓ Messages Page:"
echo "  - Click 'Message Teacher'"
echo "  - Messages list displays"
echo "  - Click a message to read"
echo "  - Message marks as read"
echo "  - Unread badge updates"
echo ""
echo "📱 MOBILE TESTING:"
echo "  - Open DevTools (F12)"
echo "  - Toggle device toolbar"
echo "  - Test on iPhone/Android sizes"
echo "  - Check touch-friendly buttons"
echo "  - Verify no horizontal scroll"
echo ""
echo "🔧 QUICK ADMIN ACCESS:"
echo "  - Login: superadmin@test.com"
echo "  - Navigate to Admin > Parents"
echo "  - Invite a parent"
echo "  - Link to a child"
echo "  - Then test as parent"
echo ""
echo "💡 TIP: Use the Admin dashboard to quickly:"
echo "   - Add children"
echo "   - Create parent accounts"
echo "   - Link parents to children"
echo "   - Then switch to parent view for testing"
echo ""
echo "🚀 Ready to test!"
echo ""
